### ISSUE TITLE
Add further options for cookie

### ISSUE THREAD

**Issue by PaoloBertuzzo** [DaWyz/hapi-session-redis#1]
Hello,
in my case "path" option is very important. Could you provide other options for cookie (e.g. the ones Hapi state exposes)?

**Comment by DaWyz** [comment]
Hi @PaoloBertuzzo, I'm gonna work on it this week. Will add the missing options for cookie to expose the same parameters Hapi state exposes.

**Comment by DaWyz** [comment]
Hi @PaoloBertuzzo, I updated the code and added the `path` option and some others too. You can check the README.md.

Hope it helps.

**Comment by PaoloBertuzzo** [comment]
Just tested, good job guys! Thank so much, really appreciated!
